#!/usr/bin/env python3
"""Extract B129 nominal pressure versus indentation from an FEBio 4.x XPLT file.

The 200 x 1 um top reaction is divided by nominal area 200 um^2.
This reader expects the mesh/node order generated by models/b129_stage1/generate_model.py.
"""
import argparse
import csv
import struct
from pathlib import Path

import numpy as np


def chunks(data, start, end):
    pos = start
    while pos < end:
        tag, length = struct.unpack_from("<II", data, pos)
        nxt = pos + 8 + length
        if nxt > end:
            raise ValueError("Invalid XPLT chunk length")
        yield tag, pos + 8, nxt
        pos = nxt
    if pos != end:
        raise ValueError("Invalid XPLT chunk boundary")


def child(data, start, end, tag):
    for item in chunks(data, start, end):
        if item[0] == tag:
            return item[1:]
    raise ValueError(f"Missing XPLT chunk {tag:#x}")


def extract(path, nx=401, ramp_um=50.0, width_um=200.0, depth_um=1.0):
    data = Path(path).read_bytes()
    if data[:4] != b"BEF\0":
        raise ValueError("Not a FEBio XPLT file")
    for tag, begin, end in chunks(data, 4, len(data)):
        if tag != 0x02000000:  # state
            continue
        h0, h1 = child(data, begin, end, 0x02010000)
        t0, _ = child(data, h0, h1, 0x02010002)
        time = struct.unpack_from("<f", data, t0)[0]
        d0, d1 = child(data, begin, end, 0x02020000)
        n0, n1 = child(data, d0, d1, 0x02020300)
        node_vars = list(chunks(data, n0, n1))
        if len(node_vars) < 2:
            raise ValueError("Reaction forces missing from nodal variables")
        r0, r1 = node_vars[1][1:]
        p0, p1 = child(data, r0, r1, 0x02020003)
        if struct.unpack_from("<I", data, p0)[0] != 0:
            raise ValueError("Unexpected XPLT region encoding")
        nbytes = struct.unpack_from("<I", data, p0 + 4)[0]
        forces = np.frombuffer(data, dtype="<f4", count=nbytes // 4, offset=p0 + 8).reshape(-1, 3)
        nz, remainder = divmod(len(forces) - 4 * nx, 2 * nx)
        if remainder or nz < 2:
            raise ValueError("Unexpected B129 node count")
        top = np.array([4 * nx + (i * 2 + j) * nz + nz - 1
                        for i in range(nx) for j in range(2)])
        pressure = forces[top, 2].sum(dtype=float) / (width_um * depth_um)
        yield time * ramp_um, pressure


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("xplt", type=Path)
    parser.add_argument("--output", type=Path, help="CSV path (stdout by default)")
    parser.add_argument("--nx", type=int, default=401)
    parser.add_argument("--ramp-um", type=float, default=50.0)
    args = parser.parse_args()
    rows = list(extract(args.xplt, nx=args.nx, ramp_um=args.ramp_um))
    if not rows:
        raise ValueError("No converged states in XPLT")
    if args.output:
        with args.output.open("w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["indentation_um", "nominal_pressure_MPa"])
            writer.writerows(rows)
    else:
        print("indentation_um,nominal_pressure_MPa")
        for displacement, pressure in rows:
            print(f"{displacement:.9g},{pressure:.9g}")


if __name__ == "__main__":
    main()
